#
# Copyright (c) 2026-present OblivRuinDev. All rights reserved.
# License terms: https://github.com/OblivRuinDev/FJGL3/blob/master/LICENSE.md
#
# Modified from LWJGL source code.
# Original copyright notice below.
#
#
# Copyright LWJGL. All rights reserved.
# License terms: https://www.lwjgl.org/license
#

# MAJOR.MINOR.REVISION [0-9].[0-9].[0-9]+[ab]?
fjglVersion=0.1.0