/*
 * Copyright (c) 2026-present OblivRuinDev. All rights reserved.
 * License terms: https://github.com/OblivRuinDev/FJGL3/blob/master/LICENSE.md
 *
 * Modified from LWJGL source code.
 * Original copyright notice below.
 */
/*
 * Copyright LWJGL. All rights reserved.
 * License terms: https://www.lwjgl.org/license
 */
package org.lwjgl.generator

import java.io.*
import java.lang.classfile.ClassBuilder
import java.lang.classfile.ClassFile
import java.lang.classfile.ClassFile.*
import java.lang.constant.ClassDesc
import java.lang.constant.ConstantDescs.*
import java.nio.file.*
import java.util.concurrent.ConcurrentLinkedQueue

internal const val HEADER = """/*
 * Copyright (c) 2026-present OblivRuinDev. All rights reserved.
 * License terms: https://github.com/OblivRuinDev/FJGL3/blob/master/LICENSE.md
 *
 * This file is generated by FJGL3's generator, which includes
 * modifications to the original LWJGL generator.
 * Original copyright notice below.
 */
 /*
 * Copyright LWJGL. All rights reserved.
 * License terms: https://www.lwjgl.org/license
 * MACHINE GENERATED FILE, DO NOT EDIT
 */
"""

internal val JAVA_KEYWORDS = setOf(
    // Java keywords
    "abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class", "const", "continue", "default", "do", "double", "else", "enum",
    "extends", "final", "finally", "float", "for", "goto", "if", "implements", "import", "instanceof", "int", "interface", "long", "native", "new", "package",
    "private", "protected", "public", "return", "short", "static", "strictfp", "super", "switch", "synchronized", "this", "throw", "throws", "transient",
    "try", "void", "volatile", "while"
)

// Character sequence used for alignment
const val t = "    " // 4 spaces

internal class Preamble {

    companion object {
        data class NativeDefine(
            val expression: String,
            val beforeIncludes: Boolean
        )

        private val EMPTY_IMPORTS = ArrayList<String>(0)
        private val EMPTY_DIRECTIVES = ArrayList<NativeDefine>(0)
    }

    private var javaImports: MutableList<String> = EMPTY_IMPORTS

    private var nativeImports: MutableList<String> = EMPTY_IMPORTS
    private var nativeDirectives: MutableList<NativeDefine> = EMPTY_DIRECTIVES

    internal val hasNativeDirectives get() = nativeImports.isNotEmpty() || nativeDirectives.isNotEmpty()

    fun javaImport(vararg classes: String) {
        if (javaImports === EMPTY_IMPORTS)
            javaImports = ArrayList(classes.size)

        classes.forEach {
            javaImports.add(it)
        }
    }

    fun nativeImport(vararg files: String) {
        if (nativeImports === EMPTY_IMPORTS)
            nativeImports = ArrayList(files.size)

        files.forEach {
            nativeImports.add(if (it.startsWith('<'))
                it
            else
                "\"$it\"")
        }
    }

    fun nativeDirective(expression: String, beforeIncludes: Boolean) {
        if (nativeDirectives === EMPTY_DIRECTIVES)
            nativeDirectives = ArrayList()

        nativeDirectives.add(NativeDefine(expression, beforeIncludes))
    }

    /** Merges [other] into this preamble, skipping imports and directives that are already present. */
    internal fun addAll(other: Preamble) {
        other.nativeImports.forEach { file ->
            if (file !in nativeImports) {
                if (nativeImports === EMPTY_IMPORTS)
                    nativeImports = ArrayList()
                nativeImports.add(file)
            }
        }
        other.nativeDirectives.forEach { define ->
            if (define !in nativeDirectives) {
                if (nativeDirectives === EMPTY_DIRECTIVES)
                    nativeDirectives = ArrayList()
                nativeDirectives.add(define)
            }
        }
    }

    fun printJava(writer: PrintWriter) {
        if (javaImports.isEmpty())
            return

        fun List<String>.print() = this.forEach { writer.println("import $it;") }

        val static = javaImports.filter { it.startsWith("static ") }
        if (static.isNotEmpty() && static.size < javaImports.size) {
            // Separate plain from static imports
            javaImports.filter { !it.startsWith("static ") }.print()
            writer.println()
            static.print()
        } else
            javaImports.print()

        writer.println()
    }

    internal fun printNative(writer: PrintWriter, transform: (String) -> String = { it }) {
        nativeDirectives
            .filter { (_, beforeIncludes) -> beforeIncludes }
            .forEach { (expression) ->
                writer.println(transform(expression))
            }

        writer.println("#include \"common_tools.h\"")
        nativeImports.forEach {
            writer.println(transform("#include $it"))
        }

        nativeDirectives
            .filter { (_, beforeIncludes) -> !beforeIncludes }
            .forEach { (expression) ->
                writer.println(transform(expression))
            }
    }

}

private val JNI_UNDERSCORE_ESCAPE_PATTERN = "_".toRegex()

internal val String.asJNIName
    get() = if (this.indexOf('_') == -1)
        this
    else
        this.replace(JNI_UNDERSCORE_ESCAPE_PATTERN, "_1")

enum class Access(val modifier: String, val flag: Int) {
    PUBLIC("public ", ACC_PUBLIC),
    INTERNAL("", 0),
    PRIVATE("private ", ACC_PRIVATE),
    PROTECTED("protected ", ACC_PROTECTED),
}

@DslMarker
annotation class GeneratorDslMarker

@GeneratorDslMarker
abstract class FakeGeneratorTarget(
    val module: Module,
    val className: String
) {
    init {
        maps.offer(this)
    }

    /** An optional sub-package of the module package. */
    var subpackage: String? = null

    val packageName get() = if (subpackage == null) module.packageName else "${module.packageName}.$subpackage"

    /** The JVM access flags of the generated (real) class. */
    var flags: Int = ACC_PUBLIC

    private class FakeField(val name: String, val type: ClassDesc, val access: Access, val isStatic: Boolean, val isFinal: Boolean)

    private class FakeMethod(
        val name: String,
        val returnType: ClassDesc,
        val parameters: List<ClassDesc>,
        val access: Access,
        val isStatic: Boolean
    )

    private class FakeConstructor(val parameters: List<ClassDesc>, val access: Access)

    private val fakeFields = ArrayList<FakeField>()
    private val fakeMethods = ArrayList<FakeMethod>()
    private val fakeConstructors = ArrayList<FakeConstructor>()

    /**
     * Declares a field for the fake Java source.
     *
     * <p>Static final fields are emitted as blank finals that are assigned in a generated static initializer. This is required because javac would otherwise
     * emit a {@code ConstantValue} attribute for primitive (and {@code String}) constants and inline them at use sites, which would leak the fake value into
     * the classes that reference this one.</p>
     */
    protected fun addFakeField(
        name: String,
        type: ClassDesc,
        access: Access = Access.PUBLIC,
        isStatic: Boolean = true,
        isFinal: Boolean = false
    ) = fakeFields.add(FakeField(name, type, access, isStatic, isFinal))
    /** Declares a method for the fake Java source. The emitted body always throws. */
    protected fun addFakeMethod(
        name: String,
        returnType: ClassDesc,
        parameters: List<ClassDesc> = emptyList(),
        access: Access = Access.PUBLIC,
        isStatic: Boolean = true
    ) = fakeMethods.add(FakeMethod(name, returnType, parameters, access, isStatic))

    /** Declares a constructor for the fake Java source. */
    protected fun addFakeConstructor(access: Access = Access.PRIVATE, parameters: List<ClassDesc> = emptyList()) =
        fakeConstructors.add(FakeConstructor(parameters, access))

    /** Subclasses declare their fake fields/methods here. It runs once, after every target has been registered and before generation. */
    protected open fun declareFake() {}

    /** Builds the real class body. */
    abstract fun ClassBuilder.gen()

    private fun classDesc() = ClassDesc.of(packageName, className)

    private fun buildClass() = ClassFile.of().build(classDesc()) {
        it.withFlags(flags)
        it.gen()
    }

    private fun writeSource(moduleRoot: String) {
        val file = Paths.get("$moduleRoot/${module.path}/src/generated/java/${packageName.replace('.', '/')}/$className.java")
        generateOutput(this@FakeGeneratorTarget, file) { out -> emitFakeJava(out) }
    }

    private fun emitFakeJava(out: PrintWriter) {
        out.print(HEADER)
        out.println("package $packageName;\n")

        val classModifiers = buildString {
            if (flags and ACC_PUBLIC != 0) append("public ")
            if (flags and ACC_FINAL != 0) append("final ")
            if (flags and ACC_ABSTRACT != 0) append("abstract ")
        }

        out.print("${classModifiers}class $className {\n\n")

        fakeFields.forEach { field ->
            out.println(
                "$t${field.access.modifier}${if (field.isStatic) "static " else ""}${if (field.isFinal) "final " else ""}${
                    field.type.displayName()
                } ${field.name};"
            )
        }

        fakeConstructors.forEach { constructor ->
            out.println("$t${constructor.access.modifier}$className(${constructor.parameters.joinToString(", ") { it.displayName() }}) {}")
        }

        fakeMethods.forEach { method ->
            val parameters = method.parameters.mapIndexed { i, type -> "${type.displayName()} param$i" }.joinToString(", ")
            out.print(
                "    ${method.access.modifier}${if (method.isStatic) "static " else ""}${method.returnType.displayName()} ${
                    method.name
                }($parameters) { throw ex(); }\n"
            )
        }

        // Assign the static final fields in the static initializer, so that javac cannot turn them into ConstantValue constants.
        val assigned = fakeFields.filter { it.isStatic && it.isFinal }
        out.print("\n    static {\n")
        if (assigned.isNotEmpty()) {
            assigned.forEach { field -> out.print("$t${t}${field.name} = ${field.type.defaultValue()};\n") }
        }
        out.print("""
        throwInit();
    }
    private static void throwInit() {
        throw new UnsupportedOperationException();
    }
    private static UnsupportedOperationException ex() {
        return new UnsupportedOperationException();
    }
}""")

    }

    private fun ClassDesc.defaultValue(): String = when (this) {
        CD_boolean -> "false"
        CD_byte,
        CD_short,
        CD_int,
        CD_char    -> "0"
        CD_long    -> "0L"
        CD_float   -> "0.0f"
        CD_double  -> "0.0"
        else       -> "null"
    }

    private fun writeClass(moduleRoot: String) {
        val file = Paths.get("$moduleRoot/${module.path}/src/generated/class/${packageName.replace('.', '/')}/$className.class")
        ensurePath(file)

        val bytes = buildClass()
        if (Files.isRegularFile(file) && Files.readAllBytes(file).contentEquals(bytes))
            return

        println("\tWRITING CLASS: $file")
        Files.write(file, bytes)
    }

    companion object {
        internal val maps = ConcurrentLinkedQueue<FakeGeneratorTarget>()

        /** Declares and writes the fake source and the real bytecode of every registered fake class. */
        fun doGen(moduleRoot: String) {
            maps.forEach {
                it.declareFake()
                it.writeSource(moduleRoot)
                it.writeClass(moduleRoot)
            }
        }
    }
}

@GeneratorDslMarker
abstract class GeneratorTarget(
    val module: Module,
    val className: String
) {

    companion object {
        private val LINKS = Pair(
            """\p{javaJavaIdentifierStart}\p{javaJavaIdentifierPart}*(?:\.\p{javaJavaIdentifierStart}\p{javaJavaIdentifierPart}*)*""",
            """\p{javaJavaIdentifierPart}+""" // Must match tokens like GL_3_BYTES (the link is #3_BYTES)
        ).let { (JAVA, NATIVE) -> """($JAVA)?(?<!&)([@\\]?#{1,2})($NATIVE+(?:\((?:(?:, )?$JAVA)*\))?)""".toRegex() }
    }

    internal open fun getSourceFileName(): String? {
        // Nasty hack to retrieve the source file that defines this template, without having to specify it explictly.
        // This enables incremental builds to work even with arbitrary file names or when multiple templates are bundled
        // in the same file (e.g. ExtensionFlags).
        try {
            throw RuntimeException()
        } catch (t: Throwable) {
            return t.stackTrace.asSequence()
                .filter { !it.className.startsWith("org.lwjgl.generator.") }
                .mapNotNull { it.fileName }
                .firstOrNull { it.endsWith(".kt") && !(this is NativeClass && it.endsWith("Binding.kt")) }
        }
    }

    internal var lmt: Long = 0L
    internal val sourceFile = getSourceFileName()
    internal open fun getLastModified(root: String, fileName: String): Long {
        val path = Paths.get(root, fileName)
        if (Files.isRegularFile(path)) {
            return path.lastModified
        }

        // Kotlin upper-cases the first letter of the file name, try lower-casing it.
        // This is necessary on case-sensitive file systems.
        val lc = Paths.get(root, "${fileName[0].lowercaseChar()}${fileName.substring(1)}")
        if (Files.isRegularFile(lc)) {
            return lc.lastModified
        }

        throw IllegalStateException("The source file for template ${module.packageKotlin}.$className does not exist ($path).")
    }

    var subpackage: String? = null
    val packageName get() = if (subpackage == null) module.packageName else "${module.packageName}.$subpackage"

    var access = Access.PUBLIC
        set(access) {
            require(access !== Access.PRIVATE) {
                "The private access modifier is illegal on top-level classes."
            }
            field = access
        }

    internal val preamble = Preamble()

    fun <T : GeneratorTarget> T.javaImport(vararg classes: String): T {
        preamble.javaImport(*classes)
        return this
    }

    fun <T : GeneratorTarget> T.nativeDirective(expression: String, beforeIncludes: Boolean = false): T {
        preamble.nativeDirective(expression, beforeIncludes)
        return this
    }

    infix fun Int.x(other: Int) = this * other

    protected fun PrintWriter.generateJavaPreamble() {
        print(HEADER)
        println("package $packageName;\n")

        preamble.printJava(this)
    }

    abstract fun PrintWriter.generateJava()

    open fun processDocumentation(documentation: String, forcePackage: Boolean = false) =
        processDocumentation(documentation, "", "", forcePackage)


    open fun getFieldLink(field: String): String? = null
    open fun getMethodLink(method: String): String? = null

    protected fun processDocumentation(
        documentation: String,
        prefixConstant: String,
        prefixMethod: String,
        forcePackage: Boolean = false,
        javadocLinkWrap: Boolean = true
    ) = documentation.replace(LINKS) { match ->
        /*
        # - normal link, apply prefix
        ## - custom link, do not transform
        @# or @## - like above, but add "see " in front
        \# - escape, replace with #
         */
        val linkMethod = match.groupValues[2]
        if (linkMethod[0] == '\\') {
            match.value.replace("\\#", "#")
        } else {
            var className = match.groupValues[1]
            var classElement = match.groupValues[3]

            if (classElement == "NULL")
                return@replace "{@code NULL}"

            val linkType = if (classElement.endsWith(')')) LinkType.METHOD else LinkType.FIELD
            var prefix = if (linkType === LinkType.FIELD) prefixConstant else prefixMethod

            linkMethod.count { it == '#' }.let { hashes ->
                if (hashes == 1) {
                    if (className.isEmpty()) {
                        val qualifiedLink = if (linkType === LinkType.FIELD)
                            getFieldLink(classElement) ?: Generator.tokens[module]!![classElement]
                        else
                            classElement.substring(0, classElement.lastIndexOf('(')).let {
                                getMethodLink(it) ?: Generator.functions[module]!![it]
                            }

                        if (qualifiedLink != null) {
                            val hashIndex = qualifiedLink.indexOf('#')

                            className = qualifiedLink.substring(0, hashIndex)
                            if (forcePackage)
                                className = "$packageName.$className"

                            prefix = qualifiedLink.substring(hashIndex + 1, qualifiedLink.length - if (linkType === LinkType.FIELD)
                                classElement.length
                            else
                                classElement.lastIndexOf('(') + 2
                            )
                        } else {
                            throw IllegalStateException("Failed to resolve link: ${match.value} in ${this.className}")
                        }
                    } else {
                        if (classElement.startsWith(prefix))
                            classElement = classElement.substring(prefix.length)
                        else
                            prefix = ""
                    }
                    linkType.create(this.className, prefix, className, classElement, if (this is NativeClass) this.postfix else "", !javadocLinkWrap)
                } else if (hashes == 2 && className.isEmpty() && linkType === LinkType.FIELD)
                    classElement
                else
                    throw IllegalStateException("Unsupported link syntax: ${match.value} in ${this.className}")
            }.let {
                val link = if (javadocLinkWrap) "{@link $it}" else it
                if (linkMethod[0] == '@')
                    "see $link"
                else
                    link
            }
        }
    }

    private enum class LinkType {
        FIELD {
            override fun create(sourceName: String, sourcePrefix: String, className: String?, classElement: String, postfix: String, skipAlias: Boolean): String {
                val source = if (className == null || className == sourceName) "" else className

                return "$source#$sourcePrefix$classElement${if (skipAlias || sourcePrefix.isEmpty()) "" else " $classElement"}"
            }
        },
        METHOD {
            override fun create(sourceName: String, sourcePrefix: String, className: String?, classElement: String, postfix: String, skipAlias: Boolean): String {
                val source = if (className == null || className == sourceName) "" else className

                val parentheses = classElement.indexOf('(')
                check(parentheses != -1) {
                    "Invalid method link: $this#$sourcePrefix$classElement"
                }

                val name = classElement.substring(0, parentheses)

                val hasParams = parentheses < classElement.length - 2
                return "$source#$sourcePrefix$name${if (hasParams) classElement.substring(parentheses) else ""}${when {
                    hasParams || skipAlias || sourcePrefix.isEmpty()
                         -> ""
                    else -> " $name"
                }}"
            }
        };

        abstract fun create(sourceName: String, sourcePrefix: String, className: String?, classElement: String, postfix: String, skipAlias: Boolean): String
    }

}

abstract class GeneratorTargetNative(
    module: Module,
    className: String,
    val nativeSubPath: String = ""
) : GeneratorTarget(module, className) {

    internal val nativeFileName
        get() = "${this.packageName.replace('.', '_')}_${this.className}"

    internal val nativeFileNameJNI = packageName
        .splitToSequence('.')
        .plus(className)
        .joinToString("_") { it.asJNIName }

    open val skipNative = false
    var cpp = false

    fun <T : GeneratorTargetNative> T.nativeImport(vararg files: String): T {
        preamble.nativeImport(*files)
        return this
    }

    protected fun PrintWriter.generateNativePreamble() {
        print(HEADER)
        preamble.printNative(this)
    }

    abstract fun PrintWriter.generateNative()

}

// ------------------------------------

fun packageInfo(
    module: Module,
    documentation: String
) {
    Generator.register(object : GeneratorTarget(module, "package-info") {
        override fun PrintWriter.generateJava() {
            print(HEADER)
            println()
            println(processDocumentation(documentation, forcePackage = true).toJavaDoc(indentation = ""))
            println("""@org.jspecify.annotations.NullMarked
package $packageName;
""")
        }
    })
}