name: FJGL CI Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

env:
  ANT_OPTS: -Xmx2G
  LWJGL_BUILD_TYPE: nightly

jobs:
  run:
    name: Build
    uses: ./.github/workflows/run.yml
    with:
      buildType: ci