name: FJGL CI Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

env:
  ANT_OPTS: -Xmx2G
  LWJGL_BUILD_TYPE: nightly

jobs:
  Build:
    uses: ./.github/workflows/run.yml
    with:
      buildType: ci

  Release:
    needs: Build
    uses: ./.github/workflows/release.yml
    secrets: inherit