# Generates javadoc for core + all bindings and uploads it to cloudflare.
# The resulting javadoc is available at https://javadoc.fjgl.oblivruin.dev
name: FJGL Javadoc generation

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  ANT_OPTS: -Xmx2G
  LWJGL_BUILD_TYPE: nightly

jobs:
  linux:
    name: Javadoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 3
          persist-credentials: false
      - name: Setup Java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'zulu'
          java-version: '25'
          check-latest: true
      - name: Install dependencies
        run: |
          git clone https://github.com/LWJGL-CI/OculusSDK.git ../OculusSDK
      - name: Generate bindings
        run: ant -emacs clean-generated generate
      - name: Build Java
        run: ant -emacs compile
      - name: Generate javadoc
        run: ant -emacs javadoc -Dcore.java25=true
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy bin/javadoc --project-name=lwjgl-javadoc --branch=main