# Reproduces the current build, synchronizes S3 and publishes a Maven release
name: FJGL Release

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

env:
  ORG_GRADLE_PROJECT_signingKeyId: 263D4349
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PWD }}
  ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USER }}
  ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PWD }}
  ANT_OPTS: -Xmx8G
  LWJGL_BUILD_TYPE: stable
  LWJGL_BUILD_OFFLINE: true

jobs:
  linux:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 3
          persist-credentials: false
      - uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92 #v6.2.0
      - name: Retrieve version & build number
        run: |
          FJGL_VERSION=$(cat gradle.properties | grep fjglVersion= | cut -d= -f2)
          echo "FJGL_VERSION=$FJGL_VERSION" >> $GITHUB_ENV
      - name: Setup Java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'zulu'
          java-version: '25'
          check-latest: true
      - name: Install dependencies
        run: |
          git clone https://github.com/LWJGL-CI/OculusSDK.git ../OculusSDK
      - name: Restore cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            bin/classes/generator
            bin/classes/templates
            bin/libs
          key: fjgl-kotlinc-${{ github.sha }}
          enableCrossOsArchive: true
          fail-on-cache-miss: true

      - name: Restore Linux x64 native cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: bin/libs/native/linux/x64
          key: fjgl-native-${{ github.sha }}-linux-x64

      - name: Restore Linux arm32 native cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: bin/libs/native/linux/arm32
          key: fjgl-native-${{ github.sha }}-linux-arm32

      - name: Restore Linux arm64 native cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: bin/libs/native/linux/arm64
          key: fjgl-native-${{ github.sha }}-linux-arm64

      - name: Restore Linux ppc64le native cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: bin/libs/native/linux/ppc64le
          key: fjgl-native-${{ github.sha }}-linux-ppc64le

      - name: Restore Linux riscv64 native cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: bin/libs/native/linux/riscv64
          key: fjgl-native-${{ github.sha }}-linux-riscv64

      - name: Restore FreeBSD x64 native cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: bin/libs/native/freebsd/x64
          key: fjgl-native-${{ github.sha }}-freebsd-x64

      - name: Restore macOS x64 native cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: bin/libs/native/macos/x64
          key: fjgl-native-${{ github.sha }}-macos-x64
          enableCrossOsArchive: true

      - name: Restore macOS arm64 native cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: bin/libs/native/macos/arm64
          key: fjgl-native-${{ github.sha }}-macos-arm64
          enableCrossOsArchive: true

      - name: Restore Windows x64 native cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: bin/libs/native/windows/x64
          key: fjgl-native-${{ github.sha }}-windows-x64
          enableCrossOsArchive: true

      - name: Restore Windows arm64 native cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: bin/libs/native/windows/arm64
          key: fjgl-native-${{ github.sha }}-windows-arm64
          enableCrossOsArchive: true


      - name: Generate bindings
        run: ant -emacs touch-kotlinc clean-generated generate
      - name: Build Java
        run: ant -emacs compile
      - name: "Package ${{env.FJGL_VERSION}}+${{env.LWJGL_BUILD}}"
        run: |
          ant -emacs release -Dbuild.version=${{env.FJGL_VERSION}} -Dbuild.revision=${{env.LWJGL_BUILD}}
          $JAVA_HOME/bin/jar cfM lwjgl.zip -C bin/RELEASE .
      - name: Publish release to Maven
        run: ./gradlew -Prelease publish --parallel --configuration-cache --max-workers=8 --info
