# Produces a new build and publishes a Maven snapshot
name: FJGL Snapshot

on:
  workflow_dispatch:
  workflow_call:


permissions:
  contents: read

env:
  ORG_GRADLE_PROJECT_signingKeyId: 5F2B1B1A
  ORG_GRADLE_PROJECT_signingKey: |
    ${{ secrets.SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PWD }}
  ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USER }}
  ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PWD }}
  ANT_OPTS: -Xmx8G
  LWJGL_BUILD_TYPE: nightly

jobs:
  linux:
    name: Snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 3
          persist-credentials: false
      - uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92 #v6.2.0
      - name: Retrieve build number
        run: |
          FJGL_VERSION=$(cat gradle.properties | grep fjglVersion= | cut -d= -f2)
          echo "FJGL_VERSION=$FJGL_VERSION" >> $GITHUB_ENV
      - name: Setup Java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'zulu'
          java-version: '25'
          check-latest: true
      - name: Install dependencies
        run: |
          git clone https://github.com/LWJGL-CI/OculusSDK.git ../OculusSDK
      - name: Generate bindings
        run: ant -emacs clean-generated generate
      - name: Build Java
        run: ant -emacs compile
      - name: "Package ${{env.FJGL_VERSION}}-snapshot+${{env.LWJGL_BUILD}}"
        run: |
          ant -emacs release -Dbuild.revision=${{env.LWJGL_BUILD}}
          $JAVA_HOME/bin/jar cfM lwjgl.zip -C bin/RELEASE .
      - name: Publish snapshot to Maven
        run: ./gradlew -Psnapshot publish --parallel --configuration-cache --max-workers=8 --info
